"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {planV3}=require("../netlify/functions/_shared/v3-pipeline");
const {buildJobInput}=require("../netlify/functions/create-image-job");
const {sanitizeClaims}=require("../netlify/functions/_shared/v3-creative-strategy");
const {layoutFor}=require("../netlify/functions/_shared/brand-compositor");
const {PLATFORM_TEMPLATES}=require("../netlify/functions/_shared/v3-layout-engine");
const {validatePlatformPayload}=require("../netlify/functions/check-scheduled-posts");
const cases=[
 ["Massage dos/zone","Tensions dorsales et sensation de lourdeur","Story",["Fantastique","Cinématographie","Architecture"],"automatic"],
 ["Massage Ayurvédique Abhyanga","Fluidité intérieure et sensation de continuité","Instagram",["Cinématographie"],"editorial"],
 ["Massage Thaï traditionnel","Mobilité dans un rythme calme","Facebook",["Architecture"],"title"],
 ["Reiki","Recentrage et calme","Story",["Fantastique"],"automatic"],
 ["Luminothérapie PSIO®","Pause lumineuse et présence","Instagram Square",[],"title"],
 ["Biorésonance quantique","Découvrir une séance encadrée non diagnostique","Google Business",["Cinématographie"],"automatic"],
 ["Prestations en entreprise","Présenter l’identité SDZ aux équipes","Google Business",[],"none"],
];
function prepared(row,index=0){return planV3({service:row[0],subject:row[1],platform:row[2],selectedRegisters:row[3],textChoice:row[4],creativeSeed:`matrix-${index}`,costMode:"test"});}
test("matrice représentative : chaque création possède une vérité V4 unique et un rapport prêt",()=>{for(const [index,row] of cases.entries()){const p=prepared(row,index),r=p.consistencyReport;assert.equal(p.version,4);assert.equal(r.authority,"SceneIntentV4");assert.equal(r.ready,true,`${row[0]}: ${r.blockingReasons}`);assert.equal(p.photoBrief.prompt,p.sceneIntent.providerPrompt);assert.equal(p.legacyProjection.sceneFamily,p.artSelection.locationFamily);assert.equal(p.legacyProjection.messageCentral,p.posterStrategy.coreTheme);assert.equal(p.legacyProjection.texteImage,[p.posterStrategy.title,p.posterStrategy.subtitle].filter(Boolean).join(" | "));assert.equal(r.checks.claimsAllowed,true);assert.equal(r.checks.layoutCollisionRisk,false);assert.equal(r.checks.platformPayloadConsistency,true);assert.equal(p.campaignCreativeDirection.service,p.contract.name);assert.doesNotMatch(JSON.stringify(p),/soulagement absolu|guérison garantie/i);const job=buildJobInput({v3Plan:p,costMode:"test",quality:"low",costCeilingConfirmed:true});assert.equal(job.prompt,p.sceneIntent.providerPrompt);assert.equal(job.costAudit.image.n,1);assert.equal(job.costAudit.imageGenerationCallCount,1);}});
test("hiérarchie éditoriale et métier reste dynamique sans imposer le soin dans la photographie narrative",()=>{const plans=cases.slice(0,6).map(prepared);assert.equal(new Set(plans.map(p=>p.posterStrategy.visualHierarchy.join("|"))).size,plans.length);for(const p of plans){assert.ok(p.posterStrategy.visualHierarchy[0]);assert.ok(p.posterStrategy.visualHierarchy[1]);assert.ok(p.posterStrategy.visualHierarchy[2]);if(p.sceneIntent.mode==="narrative_consequence"){assert.equal(p.sceneIntent.serviceRole,"invisible_cause");assert.doesNotMatch(p.photoBrief.prompt,/praticien et bénéficiaire tous deux visibles|table de massage/i);}}});
test("preuves visibles uniquement quand le mode le justifie : narration, produit, composite ou démonstration",()=>{const thai=prepared(cases[2],2),reiki=prepared(cases[3],3),psio=prepared(cases[4],4),bio=prepared(cases[5],5);assert.equal(thai.sceneIntent.mode,"narrative_consequence");assert.doesNotMatch(thai.photoBrief.prompt,/futon au sol.*habillée/i);assert.equal(reiki.sceneIntent.mode,"narrative_consequence");assert.doesNotMatch(reiki.photoBrief.prompt,/imposition des mains sans contact/i);assert.equal(psio.sceneIntent.mode,"product_fidelity");assert.equal(psio.psioRequired,true);assert.match(psio.photoBrief.prompt,/lunettes PSiO® officielles/i);assert.match(bio.photoBrief.prompt,/non diagnostique|sans promesse médicale|non médical/i);assert.doesNotMatch(bio.photoBrief.prompt,/scanner inventé.*autorisé/i);});
test("les règles d'allégations couvrent toutes les sorties textuelles par catégories",()=>{for(const claim of ["guérison garantie","résultat total","soulagement absolu","disparition définitive","souffrent de douleurs localisées"]){const result=sanitizeClaims(claim);assert.equal(result.ok,false);assert.doesNotMatch(result.text,/guérison|garanti|absolu|définitive|souffrent de douleurs/i);}});
test("tous les templates réservent des zones titre et logo disjointes",()=>{for(const [platform,template] of Object.entries(PLATFORM_TEMPLATES)){const l=layoutFor(template.width,template.height,platform,"",platform!=="Google Business",{template}),verticalMargin=Math.max(24,Math.round(template.height*.035));assert.ok(l.textArea.bottom<=l.logoArea.top,platform);assert.ok(l.logoArea.bottom<=template.height-verticalMargin,platform);assert.ok(l.x>=template.width*.045,platform);}});
test("le contrôle est transversal et ne contient aucun titre, lieu ou zone Golden codé",()=>{const source=fs.readFileSync(path.join(__dirname,"../netlify/functions/_shared/v3-consistency-control.js"),"utf8");assert.doesNotMatch(source,/QUAND LE DOS|pavillon lacustre|Massage dos\/zone/i);assert.match(source,/subjectBrief|contract|artDirection|platform/);});
test("préparation, rapport et recomposition restent à zéro appel Images exécuté",()=>{const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");assert.match(html,/Prévisualisation gratuite V3/);assert.match(html,/consistencyReport:flow\.v3Plan\.consistencyReport/);assert.match(html,/Recomposition Sharp gratuite — 0 appel Images/);});
test("payload Make refuse une plateforme ou un texte différents de la validation",()=>{const p=prepared(cases[1],1),base={platform:"Instagram",postCopyStrategy:p.postCopyStrategy,textFinal:"Texte validé",validatedText:"Texte validé",altText:"Scène",validatedAltText:"Scène"};assert.equal(validatePlatformPayload(base),true);assert.throws(()=>validatePlatformPayload({...base,platform:"Facebook"}),/plateforme incohérent/);assert.throws(()=>validatePlatformPayload({...base,textFinal:"Texte remplacé"}),/différent du texte validé/);});