"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const MENU=require("../v3-service-menu");
const {SERVICE_REGISTRY,GENERIC_SUBJECT_CONTRACT,getServiceContract,REQUIRED_FIELDS}=require("../netlify/functions/_shared/v3-registry");
const {planV3,withPsioReferenceStatus}=require("../netlify/functions/_shared/v3-pipeline");
const {statusFromRecords,PSIO_REFERENCES}=require("../netlify/functions/_shared/v3-psio-references");
const {buildJobInput}=require("../netlify/functions/create-image-job");
const {validatePlatformPayload}=require("../netlify/functions/check-scheduled-posts");
const {PLATFORM_TEMPLATES,normalizePlatform}=require("../netlify/functions/_shared/v3-layout-engine");
const html=fs.readFileSync(path.join(__dirname,"../index.html"),"utf8");
const platforms=["Instagram","Facebook","Google Business","Story","Instagram Square"];
const registers=[[],["Cinématographie"],["Architecture"],["Fantastique"],["Fantastique","Cinématographie","Architecture"]];
const textModes=["none","title","automatic","complete"];
function category(c){if(c.generic)return "tous sujets";if(c.type==="offre composite")return "pack combiné";if(/enfant/i.test(c.name))return "enfant accompagné";if(/enceinte/i.test(c.name))return "femme enceinte";if(/entreprise/i.test(c.name))return "entreprise";if(/PSIO/i.test(c.name))return "PSiO®";if(/Biorésonance/i.test(c.name))return "biorésonance";if(/Reiki/i.test(c.name))return "Reiki adulte";if(/énergétique/i.test(c.name))return "soin énergétique";if(/Thaï traditionnel/i.test(c.name))return "massage habillé sur futon";if(/dos\/zone|Réflexologie|visage|minceur/i.test(c.name))return "prestation ciblée";if(/massage/i.test(c.type))return "massage sur table";return c.type;}
function subjectFor(c){return c.generic?"Actualité de La Santé des Zèbres":`${c.recognition} — ${c.requiredAction}`;}
function readyPlan(input){let plan=planV3(input);if(plan.psioRequired){const records=Object.fromEntries(PSIO_REFERENCES.map(ref=>[ref.id,{dataUrl:"data:image/png;base64,AA==",updatedAt:1}]));plan=withPsioReferenceStatus(plan,statusFromRecords(records,true));}return plan;}
function makeScenario(name,index){const c=getServiceContract(name),platform=platforms[index%platforms.length],textChoice=textModes[index%textModes.length],selectedRegisters=registers[index%registers.length],subject=subjectFor(c);const plan=readyPlan({service:name,platform,subject,textChoice,selectedRegisters,creativeSeed:`canonical-menu-${index}`,costMode:"test"});const job=buildJobInput({v3Plan:plan,costMode:"test",quality:"low",costCeilingConfirmed:true});return {index,name,kind:c.generic?"Tous sujets":"prestation",category:category(c),subject,platform,format:PLATFORM_TEMPLATES[normalizePlatform(platform)].ratioVariant,textMode:textChoice,registers:selectedRegisters,contract:c,plan,job};}
test("la source canonique réellement affichée contient exactement 18 prestations et Tous sujets",()=>{assert.match(html,/src="\.\/v3-service-menu\.js"/);assert.match(html,/SERVICE_MENU\.options\.map/);assert.doesNotMatch(html,/el\("option",\{value:""\}, "Non spécifiée"\)/);assert.equal(MENU.businessNames.length,18);assert.equal(MENU.options.length,19);assert.equal(MENU.options.filter(x=>x.value===MENU.ALL_SUBJECTS).length,1);assert.equal(MENU.options.filter(x=>x.kind==="service").length,18);assert.equal(new Set(MENU.options.map(x=>x.value)).size,19);assert.ok(MENU.options.every(x=>x.value.trim()&&x.label.trim()));assert.deepEqual(Object.keys(SERVICE_REGISTRY),[...MENU.businessNames]);assert.equal(SERVICE_REGISTRY[MENU.ALL_SUBJECTS],undefined);});
test("les 18 prestations canoniques ont un contrat officiel complet",()=>{for(const name of MENU.businessNames){const c=SERVICE_REGISTRY[name];assert.ok(c,name);for(const field of REQUIRED_FIELDS)assert.notEqual(c[field],undefined,`${name}.${field}`);for(const field of ["recognition","requiredAction","allowedEquipment","forbiddenEquipment","forbiddenAccessories","outfit","position","bodyZones","emotion"])assert.ok(String(c[field]).trim(),`${name}.${field}`);}});
test("les 18 préparations gratuites couvrent exactement le menu et restent cohérentes",()=>{const seen=new Set();for(const [index,name] of MENU.businessNames.entries()){const s=makeScenario(name,index),{contract:c,plan:p,job}=s;assert.equal(seen.has(name),false);seen.add(name);assert.equal(p.contract.name,name);assert.equal(p.consistencyReport.ready,true,`${name}: ${p.consistencyReport.blockingReasons}`);assert.match(p.photoBrief.prompt,new RegExp(c.requiredAction.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.recognition.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.outfit.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.position.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.bodyZones.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.allowedEquipment.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.match(p.photoBrief.prompt,new RegExp(c.forbiddenEquipment.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"));assert.equal(p.legacyProjection.caracteristiquePrestationVisible,c.recognition);assert.equal(p.postCopyStrategy.validatedBenefits[0],c.emotion);assert.doesNotMatch(JSON.stringify(p),/\b\d+[,.]?\d*\s*€|durée inventée/i);assert.equal(job.prompt,p.photoBrief.prompt);assert.equal(job.costAudit.image.n,1);assert.equal(job.costAudit.imageGenerationCallCount,1);assert.equal(p.consistencyReport.checks.platformPayloadConsistency,true);const text=`Texte validé ${name}`;assert.equal(validatePlatformPayload({platform:s.platform,postCopyStrategy:p.postCopyStrategy,textFinal:text,validatedText:text}),true);}assert.equal(seen.size,18);});
test("Tous sujets possède un contrat séparé et quatre préparations sans prestation inventée",()=>{assert.equal(GENERIC_SUBJECT_CONTRACT.generic,true);const subjects=["Actualité de La Santé des Zèbres","Offrir une attention avec un bon cadeau","Reprise après une pause estivale","Retrouver de l’élan dans une période chargée"];for(const [index,subject] of subjects.entries()){const s=makeScenario(MENU.ALL_SUBJECTS,18+index),p=readyPlan({...s.plan.artDirection,service:MENU.ALL_SUBJECTS,platform:platforms[index],subject,textChoice:textModes[index],selectedRegisters:registers[index],creativeSeed:`generic-${index}`,costMode:"test"});assert.equal(p.contract.generic,true);assert.equal(p.consistencyReport.ready,true);assert.equal(p.subjectBrief.rawSubject,subject);assert.doesNotMatch(p.photoBrief.prompt,new RegExp(MENU.businessNames.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|"),"i"));assert.doesNotMatch(p.photoBrief.prompt,/\b\d+[,.]?\d*\s*€|durée\s*:/i);assert.equal(p.psioRequired,false);}});
test("transition prestation A → Tous sujets → prestation B ne fuit aucun état",()=>{const a=makeScenario(MENU.businessNames[0],0).plan,g=readyPlan({service:MENU.ALL_SUBJECTS,platform:"Story",subject:"Fermeture exceptionnelle du cabinet",creativeSeed:"transition-generic"}),b=makeScenario(MENU.businessNames[1],1).plan;assert.notEqual(a.contract.name,b.contract.name);for(const foreign of [a.contract.name,a.contract.requiredAction,a.contract.bodyZones,b.contract.name,b.contract.requiredAction,b.contract.bodyZones])assert.equal(JSON.stringify(g).includes(foreign),false,`fuite dans Tous sujets: ${foreign}`);for(const foreign of [a.contract.name,a.contract.requiredAction])assert.equal(JSON.stringify(b).includes(foreign),false,`fuite A → B: ${foreign}`);assert.equal(g.contract.name,MENU.ALL_SUBJECTS);assert.equal(b.contract.name,MENU.businessNames[1]);});
test("la couverture par paires inclut plateformes, formats, modes et registres demandés",()=>{const scenarios=MENU.options.map((x,i)=>makeScenario(x.value,i));const values=key=>new Set(scenarios.map(x=>x[key]));for(const platform of platforms)assert.ok(values("platform").has(platform),platform);for(const mode of textModes)assert.ok(values("textMode").has(mode),mode);for(const register of ["Cinématographie","Architecture","Fantastique"])assert.ok(scenarios.some(x=>x.registers.includes(register)),register);assert.ok(scenarios.some(x=>x.registers.length===0));assert.ok(scenarios.some(x=>x.registers.length===3));for(const ratio of ["9x16-fullscreen","4x5-feed","1x1-feed","4x3-local"])assert.ok(values("format").has(ratio),ratio);assert.equal(scenarios.find(x=>x.platform==="Google Business").plan.posterStrategy.textMode,"TEXT_MODE_NONE");});
