"use strict";
const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const sharp=require("sharp");
const {SERVICE_REGISTRY,REQUIRED_FIELDS,validateRegistry,getServiceContract}=require("../netlify/functions/_shared/v3-registry");
const {ART_DIRECTION_FIELDS,createArtDirectionBrief,buildPhotoBrief}=require("../netlify/functions/_shared/v3-art-direction");
const {PLATFORM_TEMPLATES,analyzeActualImage,chooseLayout}=require("../netlify/functions/_shared/v3-layout-engine");
const {assessQuality}=require("../netlify/functions/_shared/v3-quality");
const {composeBrandPoster,BRAND_CONTACTS}=require("../netlify/functions/_shared/brand-compositor");
const root=path.resolve(__dirname,"..");

test("le registre couvre exactement les 18 prestations du menu avec tous les contrats",()=>{assert.equal(Object.keys(SERVICE_REGISTRY).length,18);assert.equal(validateRegistry(),true);for(const c of Object.values(SERVICE_REGISTRY))for(const f of REQUIRED_FIELDS)assert.notEqual(c[f],undefined,`${c.name}.${f}`);});
test("le brief DA V3 expose tous les champs puis une photographie brute sans identité",()=>{const art=createArtDirectionBrief({service:"Massage Zébré",platform:"Instagram"});for(const f of ART_DIRECTION_FIELDS)assert.notEqual(art[f],undefined,f);const photo=buildPhotoBrief(art);assert.match(photo.prompt,/Photographie éditoriale premium destinée à être mise en page ultérieurement, noir et or, jamais 3D ni illustration/);assert.match(photo.prompt,/aucun texte, aucun logo, aucune signature, aucune adresse, aucun CTA, aucun pictogramme, aucun cadre graphique/);});
test("90 décisions prestation × cinq plateformes reposent sur l'analyse réelle",()=>{const platforms=["Instagram","Facebook","Story","Google Business","Blog"];let n=0;for(const contract of Object.values(SERVICE_REGISTRY))for(const platform of platforms){const analysis=analyzeActualImage({peopleCount:contract.people,density:.3,calmZones:["top-left"],negativeSpace:["top-left"],faces:Array(contract.people).fill({})});const picked=chooseLayout({platform,contract,analysis});assert.equal(picked.platform,platform);assert.match(picked.rationale,/image réelle/);assert.ok(PLATFORM_TEMPLATES[platform].layouts.includes(picked.family));n++;}assert.equal(n,90);assert.notDeepEqual(PLATFORM_TEMPLATES.Facebook,PLATFORM_TEMPLATES.Instagram);});
test("Gold impose trois étapes Storytelling et refuse un massage seul",()=>{const c=getServiceContract("Offre Gold");assert.equal(c.recommendedLayout,"Storytelling");assert.match(c.requiredAction,/massage.*Reiki.*PSiO/i);const q=assessQuality({contract:c,analysis:{peopleCount:2,requiredActionVisible:true,businessCompliance:true,equipment:["table"],compositeStages:["massage"]},composition:{imageExists:true,paletteDrift:0}});assert.equal(q.ok,false);assert.ok(q.business.errors.includes("offre_composite_incomplete"));assert.equal(q.preserveRawImage,true);});
test("Gold complète et Sylver complète passent la conformité métier",()=>{for(const [name,stages] of [["Offre Gold",["massage","Reiki","PSiO"]],["Offre Sylver",["Abhyanga","PSiO"]]]){const c=getServiceContract(name);const q=assessQuality({contract:c,analysis:{peopleCount:2,requiredActionVisible:true,businessCompliance:true,equipment:["table","lunettes PSiO® officielles"],compositeStages:stages},composition:{imageExists:true,paletteDrift:.1}});assert.equal(q.business.ok,true,name);}});
test("PSiO interdit tout appareil inventé et limite ses références au plan PSiO",()=>{const c=getServiceContract("Luminothérapie PSIO®");assert.match(c.forbiddenEquipment,/scanner.*boîtier générique.*câbles inventés/i);assert.match(c.referencePolicy,/uniquement dans le plan réellement centré PSiO/i);const q=assessQuality({contract:c,analysis:{peopleCount:1,requiredActionVisible:true,businessCompliance:true,equipment:["scanner inventé"]},composition:{imageExists:true}});assert.equal(q.business.ok,false);});
test("une dérive ambre modérée avertit sans bloquer, une forte dérive bloque",()=>{const contract=getServiceContract("Reiki");const base={contract,analysis:{peopleCount:2,requiredActionVisible:true,businessCompliance:true,equipment:[]}};const moderate=assessQuality({...base,composition:{imageExists:true,paletteDrift:.25}});assert.equal(moderate.ok,true);assert.equal(moderate.warnings.length,1);assert.equal(assessQuality({...base,composition:{imageExists:true,paletteDrift:.7}}).ok,false);});
test("coordonnées et URL officielles sont verrouillées",()=>{assert.deepEqual(BRAND_CONTACTS,{domain:"la-sante-des-zebres.com",phone:"06.84.40.69.54",address:"11 cour Dupas, Raismes",email:"fabien.ducant@gmail.com"});});
test("Google Business sans accroche garde le logo intégral dans sa marge basse",async()=>{const image=await sharp({create:{width:1200,height:900,channels:4,background:"#17120b"}}).png().toBuffer();const logo=fs.readFileSync(path.join(root,"icons/icon-512.png"));const out=await composeBrandPoster({imageBuffer:image,logoDataUrl:`data:image/png;base64,${logo.toString("base64")}`,platform:"Google Business",headline:"",zoneText:"bottom"});const meta=await sharp(out).metadata();assert.equal(meta.width,1200);assert.equal(meta.height,900);assert.ok(out.length>10000);});
test("la photographie refusée est conservée et le texte reste indépendant",()=>{const worker=fs.readFileSync(path.join(root,"netlify/functions/process-image-job-background.js"),"utf8");const textFn=fs.readFileSync(path.join(root,"netlify/functions/generate-text.js"),"utf8");assert.match(worker,/raw-result/);assert.match(worker,/preserved:true/);assert.doesNotMatch(textFn,/process-image-job|image-job-background/);const q=assessQuality({contract:getServiceContract("Reiki"),analysis:{peopleCount:0,requiredActionVisible:false},composition:{imageExists:false}});assert.equal(q.preserveRawImage,true);assert.equal(q.preservePostText,true);});
