"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),sharp=require("sharp");
const {ART_WORLDS,LOCATIONS,ABSOLUTE_EXCLUSIONS,ANTI_REPETITION_ELEMENTS,selectArtDirection,makeArtFingerprint}=require("../netlify/functions/_shared/v3-art-worlds");
const {planV3,validatePreparedPlan}=require("../netlify/functions/_shared/v3-pipeline");
const {SERVICE_REGISTRY}=require("../netlify/functions/_shared/v3-registry");
const {PLATFORM_TEMPLATES,chooseLayout,analyzeActualImage}=require("../netlify/functions/_shared/v3-layout-engine");
const {COST_MODES,buildCostAudit}=require("../netlify/functions/_shared/v3-cost-control");
const {CAMPAIGN_FORMATS,runMasterCampaign,recomposeMasterCampaign}=require("../netlify/functions/_shared/v3-campaign");
const {composeBrandPoster,loadOfficialLogoAsset,auditLogoTransparency,hasOpaqueLogoRectangle}=require("../netlify/functions/_shared/brand-compositor");
const {buildJobInput}=require("../netlify/functions/create-image-job");
const root=path.resolve(__dirname,"..");

test("24 univers pilotés par historique évitent la répétition immédiate sans bannir l'architecture",()=>{assert.equal(ART_WORLDS.length,24);const first=selectArtDirection({seed:"a"});const second=selectArtDirection({seed:"a",history:[{artWorld:first.artWorld,architectureType:first.architectureType,primarySymbol:first.primarySymbol}]});assert.notEqual(second.artWorld,first.artWorld);assert.match(second.reasonForDifference,/différent/i);assert.ok(ART_WORLDS.some(x=>/Arcade|Architecture/i.test(x)));});
test("les 18 contrats portent reconnaissance, variété et anti-répétition",()=>{assert.equal(Object.keys(SERVICE_REGISTRY).length,18);for(const c of Object.values(SERVICE_REGISTRY)){assert.ok(c.compatibleArtWorlds.length>=3);assert.ok(c.visualNarrativeVariants.length>=3);assert.ok(c.requiredRealityAnchors.length);assert.ok(c.allowedSymbolicAmplifiers.length);assert.ok(c.forbiddenSubstitutions.length);assert.ok(c.minimumRecognitionEvidence>=1);assert.ok(c.antiRepetitionWindow>=5);}});
test("modes coût: test par défaut, production confirmée, recomposition zéro image",()=>{const t=buildJobInput({prompt:"x",v3:{service:"Reiki",platform:"Story"}});assert.equal(t.costMode,"test");assert.equal(t.quality,"low");assert.equal(t.costAudit.image.n,1);assert.equal(t.costAudit.image.retries,0);assert.throws(()=>buildJobInput({prompt:"x",costMode:"production"}),/confirmation/i);const p=buildJobInput({prompt:"x",costMode:"production",costConfirmed:true,costCeilingConfirmed:true});assert.equal(p.quality,"high");assert.equal(buildCostAudit({mode:"recompose"}).image.calls,0);assert.equal(COST_MODES.recompose.estimatedPhotoEur,0);});
test("les 18 prestations disposent de 126 décisions sur sept formats",()=>{let n=0;for(const c of Object.values(SERVICE_REGISTRY))for(const platform of CAMPAIGN_FORMATS){const l=chooseLayout({platform,contract:c,analysis:analyzeActualImage({peopleCount:c.people,density:.4,calmZones:["bottom"]})});assert.equal(l.template.width,PLATFORM_TEMPLATES[platform].width);n++;}assert.equal(n,126);});
test("campagne compatible: une photo, une vision, sept Sharp; recomposition: zéro appel payant",async()=>{let photos=0,visions=0,compositions=0;const callbacks={generateMaster:async()=>{photos++;return Buffer.from("master")},analyzeMaster:async()=>{visions++;return {sourceWidth:1920,sourceHeight:1920,protectedZones:[]}},composePlatform:async({platform})=>{compositions++;return platform}};const campaign=await runMasterCampaign(callbacks);assert.deepEqual(campaign.counters,{imageGenerationCalls:1,visionCalls:1,platformCompositions:7});assert.equal(photos,1);assert.equal(visions,1);assert.equal(compositions,7);const again=await recomposeMasterCampaign({masterRawImage:campaign.masterRawImage,masterImageAnalysis:campaign.masterImageAnalysis,composePlatform:callbacks.composePlatform});assert.equal(again.counters.imageGenerationCalls,0);assert.equal(again.counters.visionCalls,0);assert.equal(photos,1);});
test("rendus Sharp réels: sept dimensions, logo statique intègre et aucun format étiré",async()=>{const fixture=await sharp({create:{width:1920,height:1920,channels:4,background:"#21190f"}}).png().toBuffer(),official=await loadOfficialLogoAsset(),audit=await auditLogoTransparency(official.buffer);assert.equal(audit.integrity,true);assert.equal(audit.fringeDetected,false);assert.equal(await hasOpaqueLogoRectangle(official.buffer),false);for(const platform of CAMPAIGN_FORMATS){const t=PLATFORM_TEMPLATES[platform];const out=await composeBrandPoster({imageBuffer:fixture,platform,headline:"DÉCOUVREZ L’OFFRE GOLD",selectedLayout:{template:t,cropPosition:"attention"}});const m=await sharp(out).metadata();assert.deepEqual([m.width,m.height],[t.width,t.height],platform);assert.equal(m.format,"png");}});
test("endpoint de recomposition garantit zéro Images et conserve les versions",()=>{const src=fs.readFileSync(path.join(root,"netlify/functions/recompose-image-job.js"),"utf8");assert.doesNotMatch(src,/api\.openai\.com|images\/generations|images\/edits/);assert.match(src,/imageGenerationCalls:0/);assert.match(src,/derivedVersions/);});

test("plan-v3 injecte intégralement le pavillon lacustre dans le prompt réellement transmis",()=>{const plan=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"gold-lacustre",artDirectionKey:"pavillon_lacustre"});const p=plan.photoBrief.prompt;assert.match(p,/ENVIRONNEMENT COMPOSÉ/i);assert.doesNotMatch(p,/UNIVERS ARTISTIQUE SÉLECTIONNÉ|pavillon lacustre ouvert/i);assert.doesNotMatch(p,/cabinet actuel premium et intime/i);assert.equal(validatePreparedPlan(JSON.parse(JSON.stringify(plan))).planId,plan.planId);});
test("Inspector, plan préparé, job et appel Images partagent strictement le même prompt",()=>{const plan=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"stable",artDirectionKey:"pavillon_lacustre"});const input=buildJobInput({prompt:"ancien cabinet statique",v3:{service:"Reiki",platform:"Facebook"},v3Plan:plan});assert.equal(input.prompt,plan.photoBrief.prompt);assert.equal(input.v3Plan.planId,plan.planId);assert.doesNotMatch(input.prompt,/ancien cabinet statique/);const html=fs.readFileSync(path.join(root,"index.html"),"utf8");assert.match(html,/const promptText = flow\.v3Plan\?\.photoBrief\?\.prompt/);assert.match(html,/v3Plan: options\.v3Plan/);assert.match(html,/v3Plan: prepared\.v3Plan/);});
test("exclusions absolues et anti-répétition distinguent pierre, spa et architecture",()=>{assert.ok(ART_WORLDS.includes("Cabinet cinématographique intime"));assert.ok(ANTI_REPETITION_ELEMENTS.includes("arcade"));assert.ok(ABSOLUTE_EXCLUSIONS.includes("galets empilés façon zen"));assert.ok(LOCATIONS.pavillon_lacustre.dominantMaterials.includes("pierre architecturale"));const allowed=selectArtDirection({seed:"arcade",artDirectionKey:"arcade_obsidienne"});assert.equal(allowed.locationFamily,"galerie d’obsidienne asymétrique");const excluded=selectArtDirection({seed:"arcade",artDirectionKey:"arcade_obsidienne",history:[{locationFamily:"galerie d’obsidienne asymétrique",artWorld:"Arcade monumentale",architectureType:"arcade d’obsidienne latérale"}]});assert.notEqual(excluded.locationFamily,allowed.locationFamily);});
test("18 prestations et sept déclinaisons conservent la direction artistique stable de campagne",async()=>{for(const service of Object.keys(SERVICE_REGISTRY)){const plan=planV3({service,platform:"Instagram",creativeSeed:`${service}-campaign`,artDirectionKey:"pavillon_lacustre"});assert.ok(plan.artSelection.locationFamily);assert.doesNotMatch(plan.photoBrief.prompt,new RegExp(plan.artSelection.locationFamily,"i"));}const master=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"same-world",artDirectionKey:"pavillon_lacustre"});const result=await recomposeMasterCampaign({masterRawImage:Buffer.from("raw"),masterImageAnalysis:{sourceWidth:1920,sourceHeight:1920,protectedZones:[],artSelection:master.artSelection},composePlatform:async({platform,masterImageAnalysis})=>({platform,world:masterImageAnalysis.artSelection.locationFamily})});assert.equal(result.counters.imageGenerationCalls,0);assert.equal(new Set(Object.values(result.outputs).map(x=>x.world)).size,1);assert.equal(Object.values(result.outputs)[0].world,"pavillon lacustre ouvert");});
test("Gold conserve ses étapes, deux identités et Fabien dans le SceneIntent V4",()=>{const plan=planV3({service:"Offre Gold",platform:"Story",artDirectionKey:"pavillon_lacustre"}),p=plan.photoBrief.prompt;assert.equal(plan.sceneIntent.mode,"composite_fidelity");assert.equal(p,plan.sceneIntent.providerPrompt);assert.match(p,/CONTINUITÉ DE L’OFFRE/i);assert.match(p,/massage au premier plan/i);assert.match(p,/massage personnalisé.*imposition des mains Reiki.*lunettes PSiO® officielles/i);assert.match(p,/exactement 2 identités uniques/i);assert.match(p,/Fabien, praticien masculin adulte/i);assert.match(p,/mêmes identités/i);});

test("Gold et Sylver exigent trois références PSiO® persistantes, les autres prestations aucune",()=>{for(const service of ["Offre Gold","Offre Sylver"]){const plan=planV3({service,platform:"Story",costMode:"test"});assert.equal(plan.psioRequired,true);assert.equal(plan.psioReferenceReady,false);assert.equal(plan.psioReferenceCount,0);assert.deepEqual(plan.psioReferenceRoles.map(x=>x.role),["profile_worn","front_worn","product"]);}const reiki=planV3({service:"Reiki",platform:"Story",costMode:"test"});assert.equal(reiki.psioRequired,false);assert.equal(reiki.psioReferenceReady,true);assert.equal(reiki.psioReferenceCount,0);});
test("les trois clés Blobs PSiO® et leurs rôles sont retrouvés puis réutilisables",async()=>{const {PSIO_REFERENCES,getPsioStatus,getPsioDataUrls}=require("../netlify/functions/_shared/v3-psio-references");const records=Object.fromEntries(PSIO_REFERENCES.map((x,i)=>[x.id,JSON.stringify({dataUrl:`data:image/png;base64,${Buffer.from(String(i)).toString("base64")}`,role:x.role,updatedAt:10+i})]));const fake={get:async key=>records[key]||null};const first=await getPsioStatus(true,fake),second=await getPsioStatus(true,fake);assert.equal(first.psioReferenceReady,true);assert.equal(first.psioReferenceCount,3);assert.deepEqual(first.psioReferenceRoles.map(x=>x.role),["profile_worn","front_worn","product"]);assert.equal(second.psioReferenceReady,true);assert.equal((await getPsioDataUrls(fake)).length,3);});
test("Mode Test est low de bout en bout et bloque toute divergence high avant Images",()=>{const testPlan=planV3({service:"Reiki",platform:"Story",costMode:"test"});const input=buildJobInput({prompt:"legacy",v3Plan:testPlan,costMode:"test",quality:"low",size:"1024x1024"});assert.equal(input.costMode,"test");assert.equal(input.requestedQuality,"low");assert.equal(input.effectiveQuality,"low");assert.equal(input.requestedSize,"1024x1024");assert.equal(input.effectiveSize,"1024x1024");assert.equal(input.costAudit.imageGenerationCallCount,1);assert.throws(()=>buildJobInput({prompt:"x",v3Plan:testPlan,costMode:"test",quality:"high"}),/Mode Test demandé, qualité haute détectée/);const production=buildJobInput({prompt:"x",costMode:"production",costConfirmed:true,costCeilingConfirmed:true,quality:"high"});assert.equal(production.effectiveQuality,"high");});
test("préflight PSiO® bloque le bouton et le job avant tout crédit, panneau Android persistant présent",()=>{const html=fs.readFileSync(path.join(root,"index.html"),"utf8"),create=fs.readFileSync(path.join(root,"netlify/functions/create-image-job.js"),"utf8"),background=fs.readFileSync(path.join(root,"netlify/functions/process-image-job-background.js"),"utf8");assert.match(html,/psioReferenceReady===true/);assert.match(html,/type:"file",accept:"image\/\*"/);assert.match(html,/Références officielles PSiO®/);assert.match(html,/Ajouter ou remplacer/);assert.match(create,/!status\.psioReferenceReady\|\|!persistent\.length/);assert.match(create,/imageGenerationCallCount:0/);assert.match(background,/Mode Test demandé, qualité haute détectée/);assert.match(background,/imageGenerationCallCount:0/);});
test("rapport V3 expose mode, qualités, dimensions, estimation et n=1; recomposition reste sans références",()=>{const audit=buildCostAudit({mode:"test",referenceImageCount:3,requestedQuality:"low",requestedSize:"1024x1024",effectiveSize:"1024x1024"});assert.equal(audit.requestedMode,"test");assert.equal(audit.effectiveMode,"test");assert.equal(audit.requestedQuality,"low");assert.equal(audit.effectiveQuality,"low");assert.equal(audit.image.n,1);assert.equal(audit.image.referenceImageCount,1);assert.equal(audit.estimateNotInvoice,true);const recomposed=buildCostAudit({mode:"recompose",imageCalls:0,visionUsage:false});assert.equal(recomposed.imageGenerationCallCount,0);assert.equal(recomposed.image.referenceImageCount,0);});

test("les références facturables ne sont jamais affichées à zéro ni exclues du total",()=>{const audit=buildCostAudit({mode:"test",referenceImageCount:1,referenceRoles:["profile_worn"]});assert.equal(audit.referenceImageInputEstimate.status,"unknown");assert.match(audit.referenceImageInputEstimate.message,/non déterminable.*non inclus/i);assert.ok(audit.estimatedTotalMax>audit.outputImageEstimate+audit.visionEstimate);assert.equal(audit.estimateConfidence,"low");assert.equal(audit.estimateNotInvoice,true);});
test("Gold Test minimise à la vue profil; Production justifiée conserve les trois vues",()=>{const {selectedReferenceRoles}=require("../netlify/functions/_shared/v3-cost-control");const available=["profile_worn","front_worn","product"];assert.deepEqual(selectedReferenceRoles("test",available),["profile_worn"]);assert.deepEqual(selectedReferenceRoles("production",available),available);assert.deepEqual(selectedReferenceRoles("recompose",available),[]);});
test("la borne haute supérieure à 0,30 € exige une confirmation supplémentaire",()=>{const audit=buildCostAudit({mode:"test",referenceImageCount:1,referenceRoles:["profile_worn"]});assert.ok(audit.estimatedTotalMax>.30);assert.equal(audit.requiresAdditionalConfirmation,true);assert.throws(()=>buildJobInput({prompt:"x",costMode:"test",referenceImageData:["data:image/png;base64,AA=="]}),/Confirmation supplémentaire requise/);const accepted=buildJobInput({prompt:"x",costMode:"test",referenceImageData:["data:image/png;base64,AA=="],costCeilingConfirmed:true});assert.equal(accepted.imageGenerationCallCount,undefined);assert.equal(accepted.costAudit.imageGenerationCallCount,1);assert.equal(accepted.costAudit.image.referenceImageCount,1);});
test("l'audit sépare sortie, références, prompt, vision et persiste l'usage observé",()=>{const usage={input_tokens:321,output_tokens:123};const audit=buildCostAudit({mode:"test",referenceImageCount:1,referenceRoles:["profile_worn"],imageUsage:usage});for(const key of ["outputImageEstimate","referenceImageInputEstimate","promptTextEstimate","visionEstimate","estimatedTotalMin","estimatedTotalMax","estimateConfidence","estimateNotInvoice"])assert.notEqual(audit[key],undefined,key);assert.deepEqual(audit.image.usage,usage);assert.equal(audit.image.calls,1);});
test("l'interface confirme mode, low, n=1, un appel, références et fourchette",()=>{const html=fs.readFileSync(path.join(root,"index.html"),"utf8");for(const pattern of [/Mode : \$\{estimate\.effectiveMode/i,/Qualité effective : \$\{estimate\.effectiveQuality/i,/n = \$\{estimate\.image\?\.n/i,/Nombre d’appels Images/i,/Références effectivement envoyées/i,/Sortie photo estimée/i,/Entrées références estimées/i,/Total estimé/i,/CONFIRMATION SUPPLÉMENTAIRE/i])assert.match(html,pattern);assert.doesNotMatch(html,/0,00 € additionnel configuré/);});
test("le background ne marque jamais les références inconnues comme gratuites",()=>{const source=fs.readFileSync(path.join(root,"netlify/functions/process-image-job-background.js"),"utf8");assert.match(source,/costDetermination:"unknown_until_billing"/);assert.match(source,/costIncludedInOutputEstimate:false/);assert.match(source,/estimatedInputImageCostEur:null/);assert.match(source,/usage:data\.usage\?\.input_tokens_details/);assert.doesNotMatch(source,/estimatedInputImageCostEur:0/);});