"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),sharp=require("sharp");
const {ART_WORLDS,LOCATIONS,ABSOLUTE_EXCLUSIONS,ANTI_REPETITION_ELEMENTS,selectArtDirection,makeArtFingerprint}=require("../netlify/functions/_shared/v3-art-worlds");
const {planV3,validatePreparedPlan}=require("../netlify/functions/_shared/v3-pipeline");
const {SERVICE_REGISTRY}=require("../netlify/functions/_shared/v3-registry");
const {PLATFORM_TEMPLATES,chooseLayout,analyzeActualImage}=require("../netlify/functions/_shared/v3-layout-engine");
const {COST_MODES,buildCostAudit}=require("../netlify/functions/_shared/v3-cost-control");
const {CAMPAIGN_FORMATS,runMasterCampaign,recomposeMasterCampaign}=require("../netlify/functions/_shared/v3-campaign");
const {composeBrandPoster,prepareLogoOverlay,hasOpaqueLogoRectangle}=require("../netlify/functions/_shared/brand-compositor");
const {buildJobInput}=require("../netlify/functions/create-image-job");
const root=path.resolve(__dirname,"..");
const logo=fs.readFileSync(path.join(root,"icons/icon-512.png"));

test("24 univers pilotés par historique évitent la répétition immédiate sans bannir l'architecture",()=>{assert.equal(ART_WORLDS.length,24);const first=selectArtDirection({seed:"a"});const second=selectArtDirection({seed:"a",history:[{artWorld:first.artWorld,architectureType:first.architectureType,primarySymbol:first.primarySymbol}]});assert.notEqual(second.artWorld,first.artWorld);assert.match(second.reasonForDifference,/différent/i);assert.ok(ART_WORLDS.some(x=>/Arcade|Architecture/i.test(x)));});
test("les 18 contrats portent reconnaissance, variété et anti-répétition",()=>{assert.equal(Object.keys(SERVICE_REGISTRY).length,18);for(const c of Object.values(SERVICE_REGISTRY)){assert.ok(c.compatibleArtWorlds.length>=3);assert.ok(c.visualNarrativeVariants.length>=3);assert.ok(c.requiredRealityAnchors.length);assert.ok(c.allowedSymbolicAmplifiers.length);assert.ok(c.forbiddenSubstitutions.length);assert.ok(c.minimumRecognitionEvidence>=1);assert.ok(c.antiRepetitionWindow>=5);}});
test("modes coût: test par défaut, production confirmée, recomposition zéro image",()=>{const t=buildJobInput({prompt:"x",v3:{service:"Reiki",platform:"Story"}});assert.equal(t.costMode,"test");assert.equal(t.quality,"low");assert.equal(t.costAudit.image.n,1);assert.equal(t.costAudit.image.retries,0);assert.throws(()=>buildJobInput({prompt:"x",costMode:"production"}),/confirmation/i);const p=buildJobInput({prompt:"x",costMode:"production",costConfirmed:true});assert.equal(p.quality,"high");assert.equal(buildCostAudit({mode:"recompose"}).image.calls,0);assert.equal(COST_MODES.recompose.estimatedPhotoEur,0);});
test("les 18 prestations disposent de 126 décisions sur sept formats",()=>{let n=0;for(const c of Object.values(SERVICE_REGISTRY))for(const platform of CAMPAIGN_FORMATS){const l=chooseLayout({platform,contract:c,analysis:analyzeActualImage({peopleCount:c.people,density:.4,calmZones:["bottom"]})});assert.equal(l.template.width,PLATFORM_TEMPLATES[platform].width);n++;}assert.equal(n,126);});
test("campagne compatible: une photo, une vision, sept Sharp; recomposition: zéro appel payant",async()=>{let photos=0,visions=0,compositions=0;const callbacks={generateMaster:async()=>{photos++;return Buffer.from("master")},analyzeMaster:async()=>{visions++;return {sourceWidth:1920,sourceHeight:1920,protectedZones:[]}},composePlatform:async({platform})=>{compositions++;return platform}};const campaign=await runMasterCampaign(callbacks);assert.deepEqual(campaign.counters,{imageGenerationCalls:1,visionCalls:1,platformCompositions:7});assert.equal(photos,1);assert.equal(visions,1);assert.equal(compositions,7);const again=await recomposeMasterCampaign({masterRawImage:campaign.masterRawImage,masterImageAnalysis:campaign.masterImageAnalysis,composePlatform:callbacks.composePlatform});assert.equal(again.counters.imageGenerationCalls,0);assert.equal(again.counters.visionCalls,0);assert.equal(photos,1);});
test("rendus Sharp réels: sept dimensions, logo détouré et aucun format étiré",async()=>{const fixture=await sharp({create:{width:1920,height:1920,channels:4,background:"#21190f"}}).png().toBuffer();const clean=await prepareLogoOverlay(logo);assert.equal(await hasOpaqueLogoRectangle(clean),false);for(const platform of CAMPAIGN_FORMATS){const t=PLATFORM_TEMPLATES[platform];const out=await composeBrandPoster({imageBuffer:fixture,logoDataUrl:`data:image/png;base64,${logo.toString("base64")}`,platform,headline:"DÉCOUVREZ L’OFFRE GOLD",selectedLayout:{template:t,cropPosition:"attention"}});const m=await sharp(out).metadata();assert.deepEqual([m.width,m.height],[t.width,t.height],platform);assert.equal(m.format,"png");}});
test("endpoint de recomposition garantit zéro Images et conserve les versions",()=>{const src=fs.readFileSync(path.join(root,"netlify/functions/recompose-image-job.js"),"utf8");assert.doesNotMatch(src,/api\.openai\.com|images\/generations|images\/edits/);assert.match(src,/imageGenerationCalls:0/);assert.match(src,/derivedVersions/);});


test("plan-v3 injecte intégralement le pavillon lacustre dans le prompt réellement transmis",()=>{const plan=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"gold-lacustre",artDirectionKey:"pavillon_lacustre"});const p=plan.photoBrief.prompt;for(const pattern of [/UNIVERS ARTISTIQUE SÉLECTIONNÉ/i,/pavillon lacustre ouvert/i,/eau noire/i,/plateforme asymétrique/i,/toiture flottante/i,/écran minéral latéral/i,/paysage, eau et ciel visibles/i,/profondeur cinématographique en trois plans/i,/reflet impossible ou brume périphérique/i,/RAISON DE DIFFÉRENCIATION/i])assert.match(p,pattern);assert.doesNotMatch(p,/cabinet actuel premium et intime/i);assert.equal(validatePreparedPlan(JSON.parse(JSON.stringify(plan))).planId,plan.planId);});
test("Inspector, plan préparé, job et appel Images partagent strictement le même prompt",()=>{const plan=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"stable",artDirectionKey:"pavillon_lacustre"});const input=buildJobInput({prompt:"ancien cabinet statique",v3:{service:"Reiki",platform:"Facebook"},v3Plan:plan});assert.equal(input.prompt,plan.photoBrief.prompt);assert.equal(input.v3Plan.planId,plan.planId);assert.doesNotMatch(input.prompt,/ancien cabinet statique/);const html=fs.readFileSync(path.join(root,"index.html"),"utf8");assert.match(html,/const promptText = flow\.v3Plan\?\.photoBrief\?\.prompt/);assert.match(html,/v3Plan: options\.v3Plan/);assert.match(html,/v3Plan: prepared\.v3Plan/);});
test("exclusions absolues et anti-répétition distinguent pierre, spa et architecture",()=>{assert.ok(ART_WORLDS.includes("Cabinet cinématographique intime"));assert.ok(ANTI_REPETITION_ELEMENTS.includes("arcade"));assert.ok(ABSOLUTE_EXCLUSIONS.includes("galets empilés façon zen"));assert.ok(LOCATIONS.pavillon_lacustre.dominantMaterials.includes("pierre architecturale"));const allowed=selectArtDirection({seed:"arcade",artDirectionKey:"arcade_obsidienne"});assert.equal(allowed.locationFamily,"galerie d’obsidienne asymétrique");const excluded=selectArtDirection({seed:"arcade",artDirectionKey:"arcade_obsidienne",history:[{locationFamily:"galerie d’obsidienne asymétrique",artWorld:"Arcade monumentale",architectureType:"arcade d’obsidienne latérale"}]});assert.notEqual(excluded.locationFamily,allowed.locationFamily);});
test("18 prestations et sept déclinaisons conservent la direction artistique stable de campagne",async()=>{for(const service of Object.keys(SERVICE_REGISTRY)){const plan=planV3({service,platform:"Instagram",creativeSeed:`${service}-campaign`,artDirectionKey:"pavillon_lacustre"});assert.ok(plan.artSelection.locationFamily);assert.match(plan.photoBrief.prompt,new RegExp(plan.artSelection.locationFamily,"i"));}const master=planV3({service:"Offre Gold",platform:"Story",creativeSeed:"same-world",artDirectionKey:"pavillon_lacustre"});const result=await recomposeMasterCampaign({masterRawImage:Buffer.from("raw"),masterImageAnalysis:{sourceWidth:1920,sourceHeight:1920,protectedZones:[],artSelection:master.artSelection},composePlatform:async({platform,masterImageAnalysis})=>({platform,world:masterImageAnalysis.artSelection.locationFamily})});assert.equal(result.counters.imageGenerationCalls,0);assert.equal(new Set(Object.values(result.outputs).map(x=>x.world)).size,1);assert.equal(Object.values(result.outputs)[0].world,"pavillon lacustre ouvert");});
test("Gold conserve trois étapes, deux identités et Fabien dans le monde architectural",()=>{const p=planV3({service:"Offre Gold",platform:"Story",artDirectionKey:"pavillon_lacustre"}).photoBrief.prompt;assert.match(p,/massage personnalisé au premier plan/i);assert.match(p,/imposition des mains Reiki/i);assert.match(p,/lunettes PSiO® officielles/i);assert.match(p,/exactement 2 identités uniques/i);assert.match(p,/praticien est obligatoirement un homme adulte, Fabien/i);assert.match(p,/soin, personnes, geste et matériel 70 %/i);});
