"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),sharp=require("sharp");
const {ART_WORLDS,selectArtDirection,makeArtFingerprint}=require("../netlify/functions/_shared/v3-art-worlds");
const {SERVICE_REGISTRY}=require("../netlify/functions/_shared/v3-registry");
const {PLATFORM_TEMPLATES,chooseLayout,analyzeActualImage}=require("../netlify/functions/_shared/v3-layout-engine");
const {COST_MODES,buildCostAudit}=require("../netlify/functions/_shared/v3-cost-control");
const {CAMPAIGN_FORMATS,runMasterCampaign,recomposeMasterCampaign}=require("../netlify/functions/_shared/v3-campaign");
const {composeBrandPoster,prepareLogoOverlay,hasOpaqueLogoRectangle}=require("../netlify/functions/_shared/brand-compositor");
const {buildJobInput}=require("../netlify/functions/create-image-job");
const root=path.resolve(__dirname,"..");
const logo=fs.readFileSync(path.join(root,"icons/icon-512.png"));

test("24 univers pilotés par historique évitent la répétition immédiate sans bannir l'architecture",()=>{assert.equal(ART_WORLDS.length,24);const first=selectArtDirection({seed:"a"});const second=selectArtDirection({seed:"a",history:[{artWorld:first.artWorld,architectureType:first.architectureType,primarySymbol:first.primarySymbol}]});assert.notEqual(second.artWorld,first.artWorld);assert.match(second.reasonForDifference,/différent/i);assert.ok(ART_WORLDS.some(x=>/Arcade|Architecture/i.test(x)));});
test("les 18 contrats portent reconnaissance, variété et anti-répétition",()=>{assert.equal(Object.keys(SERVICE_REGISTRY).length,18);for(const c of Object.values(SERVICE_REGISTRY)){assert.ok(c.compatibleArtWorlds.length>=3);assert.ok(c.visualNarrativeVariants.length>=3);assert.ok(c.requiredRealityAnchors.length);assert.ok(c.allowedSymbolicAmplifiers.length);assert.ok(c.forbiddenSubstitutions.length);assert.ok(c.minimumRecognitionEvidence>=1);assert.ok(c.antiRepetitionWindow>=5);}});
test("modes coût: test par défaut, production confirmée, recomposition zéro image",()=>{const t=buildJobInput({prompt:"x",v3:{service:"Reiki",platform:"Story"}});assert.equal(t.costMode,"test");assert.equal(t.quality,"low");assert.equal(t.costAudit.image.n,1);assert.equal(t.costAudit.image.retries,0);assert.throws(()=>buildJobInput({prompt:"x",costMode:"production"}),/confirmation/i);const p=buildJobInput({prompt:"x",costMode:"production",costConfirmed:true});assert.equal(p.quality,"high");assert.equal(buildCostAudit({mode:"recompose"}).image.calls,0);assert.equal(COST_MODES.recompose.estimatedPhotoEur,0);});
test("les 18 prestations disposent de 126 décisions sur sept formats",()=>{let n=0;for(const c of Object.values(SERVICE_REGISTRY))for(const platform of CAMPAIGN_FORMATS){const l=chooseLayout({platform,contract:c,analysis:analyzeActualImage({peopleCount:c.people,density:.4,calmZones:["bottom"]})});assert.equal(l.template.width,PLATFORM_TEMPLATES[platform].width);n++;}assert.equal(n,126);});
test("campagne compatible: une photo, une vision, sept Sharp; recomposition: zéro appel payant",async()=>{let photos=0,visions=0,compositions=0;const callbacks={generateMaster:async()=>{photos++;return Buffer.from("master")},analyzeMaster:async()=>{visions++;return {sourceWidth:1920,sourceHeight:1920,protectedZones:[]}},composePlatform:async({platform})=>{compositions++;return platform}};const campaign=await runMasterCampaign(callbacks);assert.deepEqual(campaign.counters,{imageGenerationCalls:1,visionCalls:1,platformCompositions:7});assert.equal(photos,1);assert.equal(visions,1);assert.equal(compositions,7);const again=await recomposeMasterCampaign({masterRawImage:campaign.masterRawImage,masterImageAnalysis:campaign.masterImageAnalysis,composePlatform:callbacks.composePlatform});assert.equal(again.counters.imageGenerationCalls,0);assert.equal(again.counters.visionCalls,0);assert.equal(photos,1);});
test("rendus Sharp réels: sept dimensions, logo détouré et aucun format étiré",async()=>{const fixture=await sharp({create:{width:1920,height:1920,channels:4,background:"#21190f"}}).png().toBuffer();const clean=await prepareLogoOverlay(logo);assert.equal(await hasOpaqueLogoRectangle(clean),false);for(const platform of CAMPAIGN_FORMATS){const t=PLATFORM_TEMPLATES[platform];const out=await composeBrandPoster({imageBuffer:fixture,logoDataUrl:`data:image/png;base64,${logo.toString("base64")}`,platform,headline:"DÉCOUVREZ L’OFFRE GOLD",selectedLayout:{template:t,cropPosition:"attention"}});const m=await sharp(out).metadata();assert.deepEqual([m.width,m.height],[t.width,t.height],platform);assert.equal(m.format,"png");}});
test("endpoint de recomposition garantit zéro Images et conserve les versions",()=>{const src=fs.readFileSync(path.join(root,"netlify/functions/recompose-image-job.js"),"utf8");assert.doesNotMatch(src,/api\.openai\.com|images\/generations|images\/edits/);assert.match(src,/imageGenerationCalls:0/);assert.match(src,/derivedVersions/);});
